-- Criação de usuários (senha inicial 123456)
select public._criar_usuario_interno('food','123456','Food','supervisor',null,2);
select public._criar_usuario_interno('anacristina','123456','Ana Cristina','supervisor',null,7);
select public._criar_usuario_interno('sertao','123456','Sertao','supervisor',null,9);
select public._criar_usuario_interno('rayan','123456','Rayan Souza de Oliveira','supervisor',null,14);
select public._criar_usuario_interno('foodnoronha','123456','Food Noronha','supervisor',null,17);
select public._criar_usuario_interno('aldomar','123456','Aldomar Umberlino da Silva','vendedor',82,null);
select public._criar_usuario_interno('ana','123456','Ana Paula Sales','vendedor',105,null);
select public._criar_usuario_interno('andre','123456','Andre Luis','vendedor',70,null);
select public._criar_usuario_interno('antonio','123456','Antonio Josivan','vendedor',158,null);
select public._criar_usuario_interno('aparecida','123456','Aparecida','vendedor',4,null);
select public._criar_usuario_interno('carla','123456','Carla','vendedor',8,null);
select public._criar_usuario_interno('edgar','123456','Edgar Almeida','vendedor',165,null);
select public._criar_usuario_interno('eduardo','123456','Eduardo Jose Pontual','vendedor',161,null);
select public._criar_usuario_interno('eric','123456','Eric Pereira','vendedor',171,null);
select public._criar_usuario_interno('fabianderson','123456','Fabianderson Felipe','vendedor',215,null);
select public._criar_usuario_interno('felipe','123456','Felipe Fernandes','vendedor',117,null);
select public._criar_usuario_interno('flavia','123456','Flavia Soares','vendedor',88,null);
select public._criar_usuario_interno('noronha','123456','Food Noronha','vendedor',174,null);
select public._criar_usuario_interno('francisco','123456','Francisco Albuquerque','vendedor',51,null);
select public._criar_usuario_interno('geraldo','123456','Geraldo Junior','vendedor',217,null);
select public._criar_usuario_interno('gerson','123456','Gerson','vendedor',63,null);
select public._criar_usuario_interno('herval','123456','Herval Galindo','vendedor',178,null);
select public._criar_usuario_interno('irene','123456','Irene Alves','vendedor',34,null);
select public._criar_usuario_interno('jeferson','123456','Jeferson da Silva Pimentel','vendedor',119,null);
select public._criar_usuario_interno('joao','123456','Joao Vitor de Souza Santos','vendedor',210,null);
select public._criar_usuario_interno('jonas','123456','Jonas Aguiar de Santana','vendedor',177,null);
select public._criar_usuario_interno('joseildo','123456','Joseildo','vendedor',22,null);
select public._criar_usuario_interno('leonardo','123456','Leonardo Inacio Dos Santos','vendedor',84,null);
select public._criar_usuario_interno('luis','123456','Luis Eduardo','vendedor',18,null);
select public._criar_usuario_interno('matheus','123456','Matheus Rocha','vendedor',54,null);
select public._criar_usuario_interno('moacir','123456','Moacir Omena Alves Costa','vendedor',45,null);
select public._criar_usuario_interno('pedro','123456','Pedro Ferreira','vendedor',140,null);
select public._criar_usuario_interno('roberto','123456','Roberto Venício Souza','vendedor',184,null);
select public._criar_usuario_interno('romulo','123456','Romulo Henrique de Barros','vendedor',81,null);
select public._criar_usuario_interno('sergiana','123456','Sergiana Maria','vendedor',194,null);
select public._criar_usuario_interno('tiago','123456','Tiago Paiva','vendedor',195,null);
select public._criar_usuario_interno('vandson','123456','Vandson Mendes da Silva','vendedor',170,null);
select public._criar_usuario_interno('wellington','123456','Wellington Bezerra de Carvalho','vendedor',101,null);
